### ISSUE TITLE
AnswerController

### ISSUE THREAD

**Issue by ousmaneTra** [ousmaneTra/zzoverflow#15]
Pourquoi tu passes par l'actoin process() puis save() pour créer une answer?

**Comment by ousmaneTra** [comment]
Si un user est connecté et repond une question une fois, à chaque fois qu'il fait GET "/answer/save" ça va recréer la même response encore

**Comment by haelbouhad** [comment]
En fait, si l'user n'est pas connecté et il rédige une réponse, dès qu'il clique sur le bouton pour soumissionner (answer/save) sa réponse, il doit etre redirigé vers la page authentification. Une fois connecté il sera redirigé cette fois ci vers l'action save du contrôleur Answer. Mais le problème aperçu c qu'on perd le contenu de sa réponse.

Ma solution consiste a passer par une action pour saauvegarder le contenuc de la réponse dans la session par process() avant dappeler save qui est annotee par secured.
